baseURL: 'https://gwei.cz/'
languageCode: cs-cz
title: gwei.cz
theme: book
enableGitInfo: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

menu:

  after:
    - name: GitHub
      url: https://github.com/gweicz
      weight: 10
    - name: Twitter
      url: https://twitter.com/gweicz
    - name: Discord (chat)
      url: https://discord.gg/FpxwbnM


params:
  BookRepo: https://github.com/gweicz/docs
  BookEditPath: edit/master/content
  BookLogo: /img/logo.png
  #BookMenuBundle: /menu

