baseURL: 'https://prirucka.gwei.cz/'
languageCode: cs-cz
title: Gwei.cz Příručka
theme: book
enableEmoji: true
enableGitInfo: true
googleAnalytics: UA-160836210-2

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

menu:

  after:
    - name: GitHub
      url: https://github.com/gweicz
      weight: 10
    - name: Twitter
      url: https://twitter.com/gweicz
      weight: 15
    - name: Discord (chat)
      url: https://discord.gg/FpxwbnM
      weight: 20
    - name: Fórum
      url: https://forum.gwei.cz
      weight: 25


params:
  BookRepo: https://github.com/gweicz/docs
  BookEditPath: edit/master/content
  BookLogo: /img/logo.png
  #BookMenuBundle: /menu

